name: build
run-name: build
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - run: mvn -U clean build
  test:
    runs-on: self-hosted
    steps:
      - run: mvn -U test
  install:
    runs-on: self-hosted
    steps:
      - run: mvn -U install
      