name: build
run-name: build
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: mvn -U clean compile
  test:
    needs: build
    runs-on: self-hosted
    steps:
      - run: mvn -U test
  install:
    needs: test
    runs-on: self-hosted
    steps:
      - run: mvn -U install
      